osx_image: xcode7.3
language: objective-c
#xcode_workspace: MKDB.xcworkspace
#xcode_scheme: MKDB
script: xcodebuild -workspace TravisExample.xcworkspace -scheme TravisExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO