
language: objective-c

osx_image: xcode7.3

before_install:

- export LANG=en_US.UTF-8
- env
- locale
- gem install cocoapods --quiet
- pod --version

script:

- pod lib lint --allow-warnings
- xctool -workspace MKDB.xcworkspace -scheme 'MKDB' -sdk iphonesimulator -arch i386 build

- pod install
- xcodebuild -workspace MKDB.xcworkspace -scheme 'MKDB' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test
